version: 2
updates:
- directory: "/"
  package-ecosystem: "github-actions"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Bucharest"
  commit-message:
    prefix: "dependabot"
    include: scope
  labels:
    - "kind/cleanup"
    - "dependabot"
- directory: "/"
  package-ecosystem: "gomod"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Bucharest"
  commit-message:
    prefix: "dependabot"
    include: scope
  ignore:
  - dependency-name: "sigs.k8s.io/controller-runtime"
  - dependency-name: "k8s.io/*"
  labels:
    - "kind/cleanup"
    - "dependabot"
