apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  namespace: cluster-registry
data:
  config.yaml: |
    apiVersion: config.registry.ethos.adobe.com/v1
    kind: ClientConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 0.0.0.0:9090
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceNamespace: cluster-registry
      resourceName: 0c4967d2.registry.ethos.adobe.com
    namespace: cluster-registry
    alertmanagerWebhook:
      bindAddress: 0.0.0.0:9092
      alertMap:
        - alertName: TestAlertMapping
          onFiring:
            my-tag: "off"
          onResolved:
            my-tag: "on"
