apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-registry-client
  labels:
    {{- include "cluster-registry-client.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - registry.ethos.adobe.com
    resources:
      - clusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - registry.ethos.adobe.com
    resources:
      - clusters/finalizers
    verbs:
      - update
  - apiGroups:
      - registry.ethos.adobe.com
    resources:
      - clusters/status
    verbs:
      - get
      - patch
      - update
