{{- if .Values.podDisruptionBudget.enabled }}
{{- if eq (.Values.replicaCount | int) (.Values.podDisruptionBudget.minAvailable| int) }}
{{- fail ".Values.replicaCount should be greater than .Values.podDisruptionBudget.minAvailable" }}
{{- else }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "cluster-registry-client.labels" . | nindent 4 }}
  name: {{ template "cluster-registry-client.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "cluster-registry-client.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
{{- end }}
