apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cluster-registry-client.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-registry-client.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cluster-registry-client.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-registry-client.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
