---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-registry
rules:
- apiGroups:
  - registry.ethos.adobe.com
  resources:
  - clusters
  - servicemetadatawatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.ethos.adobe.com
  resources:
  - clusters/finalizers
  - servicemetadatawatchers/finalizers
  verbs:
  - update
- apiGroups:
  - registry.ethos.adobe.com
  resources:
  - clusters/status
  - servicemetadatawatchers/status
  verbs:
  - get
  - patch
  - update
