apiVersion: v2
name: cluster-registry-client
description: Helm chart for Cluster Registry Client.
type: application
home: https://github.com/adobe/cluster-registry

maintainers:
- name: aalexandru
- name: radu-catalina

version: 0.1.0
appVersion: "v1.4.0"
