apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-registry-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-registry-client.componentLabels" . | nindent 4 }}
