apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-registry-sync-manager.fullname" . }}
  labels:
    {{- include "cluster-registry-sync-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-registry-sync-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-registry-sync-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
