nameOverride: "cluster-registry-client"
fullnameOverride: "cluster-registry-client"

replicaCount: 2

clusterRegistryClient:
  alertmanagerWebhook:
    bindAddress: 0.0.0.0:9092
    alertMap: []
  health:
    healthProbeBindAddress: :8081
  metrics:
    bindAddress: 0.0.0.0:9090
  webhook:
    port: 9443
  leaderElection:
    leaderElect: true
    resourceNamespace: cluster-registry
    resourceName: 0c4967d2.registry.ethos.adobe.com

rbac:
  create: true
  nameSuffix: "cluster-client"

serviceAccount:
  # Specifies whether a service account should be created, else use: 'name: "default"''
  create: true
  # The name of the service account to use.
  # If set, override, else will use chart fullname template
  name: "cluster-registry-client"

image:
  pullPolicy: "IfNotPresent"
  registry: "ghcr.io/adobe/cluster-registry-client"

ports:
  - name: metrics
    containerPort: 9090
  - name: amwebhook
    containerPort: 9092

resources:
  limits:
    cpu: 200m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 200Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 9091
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 9091
  initialDelaySeconds: 5
  periodSeconds: 10

terminationGracePeriodSeconds: 10
