//go:build !ignore_autogenerated

/*
Copyright 2021 Adobe. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMetadataWatcher) DeepCopyInto(out *ServiceMetadataWatcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMetadataWatcher.
func (in *ServiceMetadataWatcher) DeepCopy() *ServiceMetadataWatcher {
	if in == nil {
		return nil
	}
	out := new(ServiceMetadataWatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceMetadataWatcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMetadataWatcherList) DeepCopyInto(out *ServiceMetadataWatcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceMetadataWatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMetadataWatcherList.
func (in *ServiceMetadataWatcherList) DeepCopy() *ServiceMetadataWatcherList {
	if in == nil {
		return nil
	}
	out := new(ServiceMetadataWatcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceMetadataWatcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMetadataWatcherSpec) DeepCopyInto(out *ServiceMetadataWatcherSpec) {
	*out = *in
	if in.WatchedServiceObjects != nil {
		in, out := &in.WatchedServiceObjects, &out.WatchedServiceObjects
		*out = make([]WatchedServiceObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMetadataWatcherSpec.
func (in *ServiceMetadataWatcherSpec) DeepCopy() *ServiceMetadataWatcherSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceMetadataWatcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMetadataWatcherStatus) DeepCopyInto(out *ServiceMetadataWatcherStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMetadataWatcherStatus.
func (in *ServiceMetadataWatcherStatus) DeepCopy() *ServiceMetadataWatcherStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceMetadataWatcherStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedField) DeepCopyInto(out *WatchedField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedField.
func (in *WatchedField) DeepCopy() *WatchedField {
	if in == nil {
		return nil
	}
	out := new(WatchedField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedServiceObject) DeepCopyInto(out *WatchedServiceObject) {
	*out = *in
	out.ObjectReference = in.ObjectReference
	if in.WatchedFields != nil {
		in, out := &in.WatchedFields, &out.WatchedFields
		*out = make([]WatchedField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedServiceObject.
func (in *WatchedServiceObject) DeepCopy() *WatchedServiceObject {
	if in == nil {
		return nil
	}
	out := new(WatchedServiceObject)
	in.DeepCopyInto(out)
	return out
}
