name: release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release-*'
    tags:
      - 'v*'

jobs:
  publish-docker-image-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ env.golang-version }}'
      - name: Login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push api and cc Docker images
        run: make release
      - name: Build and push performance tests Docker image
        run: make release-performance
      - name: Build and push SLTs Docker image
        run: make release-slt
